name: ui_showroom
description: UI Library Showroom.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: "2.10.4"

dependencies:
  flutter:
    sdk: flutter
  dropdown_button2: ^1.4.0
  provider: ^6.0.2
  ui_library:
    path: '../ui_library'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  assets:
    - images/
