# Pre-Commit E2E Tests in iOS
name: Running Appium Tests on iOS

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
  
jobs:
  test:
    runs-on: macOS-latest
    steps:
    - name: Checkout working directory ğŸ”–
      uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.10.4'
        channel: 'stable' 

    - name: Use Node.js ${{ matrix.node-version }} ğŸ”¨
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install NPM dependencies ğŸ“¦
      working-directory: appium-tests
      run: npm ci

    - name: Load iOS Simulator ğŸ“±
      uses: futureware-tech/simulator-action@v1 # install and create the Emulator
      with:
        model: 'iPhone 11'
    
    - name: Install and Run Appium Server ğŸ–¥ï¸
      run: |
        chmod +x ./appium-tests/scripts/run_appium_server.sh # install and run appium server in the background
        ./appium-tests/scripts/run_appium_server.sh

    - name: Build iOS App
      run: |
        flutter build ios --debug --no-codesign
        cp -r build/ios/iphoneos appium-tests/apps
      
    - name: Run Appium Tests ğŸŒ¡ï¸
      working-directory: appium-tests
      run: |
        npm run ios.ci

    - name: Upload Screenshots if tests failed ğŸ“·
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: appium-screenshots
        path: appium-tests/test-results/ios