# Pre-Commit E2E Tests in iOS
name: Running Appium Tests on iOS

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
  
jobs:
  build:
    runs-on: macOS-latest
    steps:
    - name: Checkout working directory ğŸ”–
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }} ğŸ”¨
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install NPM dependencies ğŸ“¦
      run: |
        cd appium-tests && npm ci

    - name: Install and Run Appium Server ğŸ–¥ï¸
      run: |
        chmod +x ./appium-tests/scripts/run_appium_server.sh # install and run appium server in the background
        ./appium-tests/scripts/run_appium_server.sh
    
    - name: Load iOS Simulator ğŸ“±
      uses: futureware-tech/simulator-action@v1 # install and create the Emulator
      with:
        model: 'Iphone 13'
        
    - name: Run Appium Tests ğŸŒ¡ï¸
      with:
        working-directory: appium-tests
        script: |
          npm run ios.ci

    - name: Upload Screenshots if tests failed ğŸ“·
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: appium-screenshots
        path: appium-tests/test-results/ios